apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v2-faulty
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: v2
  template:
    metadata:
      labels:
        app: nginx
        version: v2
    spec:
      serviceAccountName: nginx
      containers:
      - name: nginx-v2-faulty
        image: nginx
        ports:
        - containerPort: 80
        args: ["nginx", "-g", "daemon off;"]
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-configmap-503 ### Deploying with the 503 configmap

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-503
  namespace: nginx
data:
  default.conf: |
    server {
      listen 80 default_server;
      listen [::]:80 default_server;
      server_name _;
      return 503;
    }
