publicIpAddress = "<Known after bicep deployment>"
adminPassword = "MyPassword@1234"
privateIpAddress = "<Known after bicep deployment>"
customHostname = "dev.csr-solutions.co.uk"
backendServerHostname = "csr-dev-uks-app.azurewebsites.net"