using '../web-app.bicep'

param project = 'csr' 
param environment = 'dev' 
param location = 'uksouth'
param location_shortCode = 'uks'
param sku = 'B1'
param customHostname = 'csr-solutions.co.uk'
param publicIPAllocationMethod = 'Static'
param publicIpSku = 'Standard'
param vmSize = 'Standard_B2s'
param addressPrefix = '10.0.0.0/16'
param subnetPrefix = '10.0.0.0/24'
param adminUsername = 'crees'
param adminPassword = 'MyPassword@1234'
